export enum PlatformType {
    PC = 'PC',
    XboxOne = 'Xbox One',
    Xbox360 = 'Xbox 360',
    XboxCloudGaming = 'Xbox Cloud Gaming',
    XboxSeriesXS = 'Xbox Series X/S',
    PS3 = 'PS3',
    PS4 = 'PS4',
    PS5 = 'PS5',
    Stadia = 'Stadia',
    Alert = 'Alert',
    Authentication = 'Authentication',
    Store = 'Store',
    CloudServices = 'Cloud Services',
    Downloads = 'Downloads',
    AllFeatures = 'All Features',
};